/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tictactoeintelligent.views;

import com.mycompany.tictactoeintelligent.controllers.MainController;
import com.mycompany.tictactoeintelligent.models.Board;

/**
 *
 * @author jhon
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private Board estadoActual;
    private MainController controlador;

    public MainFrame() {
        initComponents();
        estadoActual = new Board();
        controlador = new MainController(estadoActual,casilla00, casilla01, casilla02, casilla10, casilla11, casilla12, casilla20, casilla21, casilla22);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        casilla00 = new javax.swing.JButton();
        casilla02 = new javax.swing.JButton();
        casilla10 = new javax.swing.JButton();
        casilla11 = new javax.swing.JButton();
        casilla12 = new javax.swing.JButton();
        casilla20 = new javax.swing.JButton();
        casilla21 = new javax.swing.JButton();
        casilla22 = new javax.swing.JButton();
        casilla01 = new javax.swing.JButton();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        casilla00.setBackground(new java.awt.Color(0, 0, 0));
        casilla00.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla00.setForeground(new java.awt.Color(255, 255, 255));
        casilla00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla00ActionPerformed(evt);
            }
        });

        casilla02.setBackground(new java.awt.Color(0, 0, 0));
        casilla02.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla02.setForeground(new java.awt.Color(255, 255, 255));
        casilla02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla02ActionPerformed(evt);
            }
        });

        casilla10.setBackground(new java.awt.Color(0, 0, 0));
        casilla10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla10.setForeground(new java.awt.Color(255, 255, 255));
        casilla10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla10ActionPerformed(evt);
            }
        });

        casilla11.setBackground(new java.awt.Color(0, 0, 0));
        casilla11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla11.setForeground(new java.awt.Color(255, 255, 255));
        casilla11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla11ActionPerformed(evt);
            }
        });

        casilla12.setBackground(new java.awt.Color(0, 0, 0));
        casilla12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla12.setForeground(new java.awt.Color(255, 255, 255));
        casilla12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla12ActionPerformed(evt);
            }
        });

        casilla20.setBackground(new java.awt.Color(0, 0, 0));
        casilla20.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla20.setForeground(new java.awt.Color(255, 255, 255));
        casilla20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla20ActionPerformed(evt);
            }
        });

        casilla21.setBackground(new java.awt.Color(0, 0, 0));
        casilla21.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla21.setForeground(new java.awt.Color(255, 255, 255));
        casilla21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla21ActionPerformed(evt);
            }
        });

        casilla22.setBackground(new java.awt.Color(0, 0, 0));
        casilla22.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla22.setForeground(new java.awt.Color(255, 255, 255));
        casilla22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla22ActionPerformed(evt);
            }
        });

        casilla01.setBackground(new java.awt.Color(0, 0, 0));
        casilla01.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        casilla01.setForeground(new java.awt.Color(255, 255, 255));
        casilla01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(casilla00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(casilla00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casilla01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void casilla00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla00ActionPerformed
        controlador.jugar(0, 0);
    }//GEN-LAST:event_casilla00ActionPerformed

    private void casilla01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla01ActionPerformed
        controlador.jugar(0, 1);
    }//GEN-LAST:event_casilla01ActionPerformed

    private void casilla02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla02ActionPerformed
        controlador.jugar(0, 2);
    }//GEN-LAST:event_casilla02ActionPerformed

    private void casilla10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla10ActionPerformed
        controlador.jugar(1, 0);
    }//GEN-LAST:event_casilla10ActionPerformed

    private void casilla11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla11ActionPerformed
        controlador.jugar(1, 1);
    }//GEN-LAST:event_casilla11ActionPerformed

    private void casilla12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla12ActionPerformed
        controlador.jugar(1, 2);
    }//GEN-LAST:event_casilla12ActionPerformed

    private void casilla20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla20ActionPerformed
        controlador.jugar(2, 0);
    }//GEN-LAST:event_casilla20ActionPerformed

    private void casilla21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla21ActionPerformed
        controlador.jugar(2, 1);
    }//GEN-LAST:event_casilla21ActionPerformed

    private void casilla22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla22ActionPerformed
        controlador.jugar(2, 2);
    }//GEN-LAST:event_casilla22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton casilla00;
    private javax.swing.JButton casilla01;
    private javax.swing.JButton casilla02;
    private javax.swing.JButton casilla10;
    private javax.swing.JButton casilla11;
    private javax.swing.JButton casilla12;
    private javax.swing.JButton casilla20;
    private javax.swing.JButton casilla21;
    private javax.swing.JButton casilla22;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
